---
AmbiguousRegexpLiteral:
  Enabled: false
AsciiComments:
  Enabled: false
AssignmentInCondition:
  Enabled: false
BlockNesting:
  Max: 4
ClassAndModuleChildren:
  Enabled: false
ClassVars:
  Enabled: false
CommentAnnotation:
  Enabled: false
CyclomaticComplexity:
  Max: 7
Documentation:
  Enabled: false
FileName:
  Enabled: false
FormatString:
  Enabled: false
HandleExceptions:
  Enabled: false
IfUnlessModifier:
  Enabled: false
IndentHash:
  Enabled: false
Lambda:
  Enabled: false
MethodLength:
  Max: 21
MultilineBlockChain:
  Enabled: false
RegexpLiteral:
  Enabled: false
SignalException:
  Enabled: false
SingleLineBlockParams:
  Enabled: false
SingleLineMethods:
  Enabled: false
SpecialGlobalVars:
  Enabled: false
StringLiterals:
  Enabled: false
TrailingComma:
  Enabled: false
TrivialAccessors:
  Enabled: false
UselessAssignment:
  Enabled: false
Void:
  Enabled: false
WordArray:
  MinSize: 3
