sudo: false
language: ruby
before_script: .travis/before.sh
install: 
  - gem install bundler
  - bundle install --deployment --without development production
rvm: 2.5.1
cache: bundler
branches:
  only:
  - master
addons:
  postgresql: "9.4"
  apt:
    packages:
    - postgresql-server-dev-9.4
